name: Push Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  pull_request:
    types: [opened, synchronize, enqueued]
    branches:
      - '**'  # All branches

  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Trying to merge ${{ github.ref }} into ${{ github.base_ref }}..."
      - name: Check out repository code - force fetch
        uses: actions/checkout@v4
        with:
          # Fetches all branches and tags and sets up a detached HEAD.
          fetch-depth: 0
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Prints out the push information
        run: |
          echo "The push information is ${{ toJson(github) }}"
      - name: Print the environment variables
        run: |
          printenv
